In [19]:
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [20]:
#Importing Dataset
X = pd.read_csv("nba.games.stats.csv")
X.head(10)

,Unnamed: 0,Team,Game,Date,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,1,ATL,1,2014-10-29,Away,TOR,L,102,109,40,...,27,33,0.818,16,48,26,13,9,9,22
1,2,ATL,2,2014-11-01,Home,IND,W,102,92,35,...,18,21,0.857,11,44,25,5,5,18,26
2,3,ATL,3,2014-11-05,Away,SAS,L,92,94,38,...,27,38,0.711,11,50,25,7,9,19,15
3,4,ATL,4,2014-11-07,Away,CHO,L,119,122,43,...,20,27,0.741,11,51,31,6,7,19,30
4,5,ATL,5,2014-11-08,Home,NYK,W,103,96,33,...,8,11,0.727,13,44,26,2,6,15,29
5,6,ATL,6,2014-11-10,Away,NYK,W,91,85,27,...,7,12,0.583,11,40,23,4,2,15,26
6,7,ATL,7,2014-11-12,Home,UTA,W,100,97,39,...,6,12,0.500,8,30,28,12,8,11,17
7,8,ATL,8,2014-11-14,Home,MIA,W,114,103,42,...,23,25,0.920,5,32,27,10,3,14,20
8,9,ATL,9,2014-11-15,Away,CLE,L,94,127,40,...,10,13,0.769,12,47,39,12,2,13,14
9,10,ATL,10,2014-11-18,Home,LAL,L,109,114,41,...,14,22,0.636,13,44,24,7,0,11,24

In [21]:
#Intitally done when we were going to use Home and Away as a category but decided to focus on the statistics within the game  redundant in final feature selection


one_hot = pd.get_dummies(X['Home'],prefix='Side')
X = X.drop('Home',axis = 1)
X = X.join(one_hot)
X.head()

,Unnamed: 0,Team,Game,Date,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,FieldGoalsAttempted,...,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls,Side_Away,Side_Home
0,1,ATL,1,2014-10-29,TOR,L,102,109,40,80,...,0.818,16,48,26,13,9,9,22,1,0
1,2,ATL,2,2014-11-01,IND,W,102,92,35,69,...,0.857,11,44,25,5,5,18,26,0,1
2,3,ATL,3,2014-11-05,SAS,L,92,94,38,92,...,0.711,11,50,25,7,9,19,15,1,0
3,4,ATL,4,2014-11-07,CHO,L,119,122,43,93,...,0.741,11,51,31,6,7,19,30,1,0
4,5,ATL,5,2014-11-08,NYK,W,103,96,33,81,...,0.727,13,44,26,2,6,15,29,0,1

In [22]:
#changing team labels to unique numbers
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
X['Team']=le.fit_transform(X['Team'])
X['Opponent']=le.transform(X['Opponent'])
X.head()

,Unnamed: 0,Team,Game,Date,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,FieldGoalsAttempted,...,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls,Side_Away,Side_Home
0,1,0,1,2014-10-29,27,L,102,109,40,80,...,0.818,16,48,26,13,9,9,22,1,0
1,2,0,2,2014-11-01,11,W,102,92,35,69,...,0.857,11,44,25,5,5,18,26,0,1
2,3,0,3,2014-11-05,26,L,92,94,38,92,...,0.711,11,50,25,7,9,19,15,1,0
3,4,0,4,2014-11-07,4,L,119,122,43,93,...,0.741,11,51,31,6,7,19,30,1,0
4,5,0,5,2014-11-08,19,W,103,96,33,81,...,0.727,13,44,26,2,6,15,29,0,1

In [23]:
#mapping a win or loss to 1=Win and Zero= loss, also feature selection is done here. 


d=X['WINorLOSS']
d=list(map(lambda x: 1 if x != 'L' else 0, d))

featuretoDrop = ['Unnamed: 0', 'Game', 'Date',  'WINorLOSS','TeamPoints',
                 'FieldGoals', 'FieldGoalsAttempted', 'FieldGoals.', 'X3PointShots', 
                 'X3PointShotsAttempted', 'X3PointShots.', 'FreeThrows', 'FreeThrowsAttempted', 
                 'FreeThrows.', 'OffRebounds', 'TotalRebounds', 'Assists','Turnovers','Opp.TotalRebounds', 'Opp.Steals', 'Opp.Blocks', 'Side_Away', 'Side_Home', 'Team', 'Opponent', 'Opp.TotalFouls']
data = X.drop(featuretoDrop, axis = 1)
data.head(15)
features=list(data)
print(features)

['OpponentPoints', 'Steals', 'Blocks', 'TotalFouls', 'Opp.FieldGoals', 'Opp.FieldGoalsAttempted', 'Opp.FieldGoals.', 'Opp.3PointShots', 'Opp.3PointShotsAttempted', 'Opp.3PointShots.', 'Opp.FreeThrows', 'Opp.FreeThrowsAttempted', 'Opp.FreeThrows.', 'Opp.OffRebounds', 'Opp.Assists', 'Opp.Turnovers']

In [24]:
from sklearn.model_selection import train_test_split
#splitting data set into training and test set
X_train, X_test, WL_train, WL_test = train_test_split(data[features], d, test_size=0.33, random_state=42)

X_train = X_train.to_numpy()
X_test = X_test.to_numpy()

In [25]:
print(X_train)

[[ 90.  11.   4. ...   8.  21.  21.]
 [ 89.   8.   5. ...  13.  16.  10.]
 [103.   6.   4. ...   9.  21.  10.]
 ...
 [120.   4.   1. ...  15.  20.  10.]
 [131.  10.   2. ...  12.  32.  14.]
 [112.   9.   2. ...   3.  20.  16.]]

In [26]:
from sklearn import svm


#training the model 
clf_svm = svm.SVC(kernel="linear", random_state=0, max_iter=3500).fit(X_train, WL_train)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)

In [27]:
predicted_svm = clf_svm.predict(X_test)#prediction of test set
#printing accuracy of predictions
correct = 0
for tag, pred in zip(WL_train, predicted_svm):   # zip allows to go through two lists simultaneously
    if (tag == pred):
        correct += 1
accuracy = correct/len(WL_test)

print(accuracy)

0.5052339901477833